name: "workflow-commands"

on: ['push']

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Maven Build"
        run: |
          echo "::group::My Group Message"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"
      - name: "Docker Build"
        run: |
          echo "::group::My Group 2 Message"
          echo "Msg-2 1"
          echo "Msg-2 2"
          echo "::endgroup::"